import React, { useState } from "react";
import axios from "axios";
import * as Spotify from "../../SpotifyAPI.js";
function TopTracksPlaylist({ userId }) {
  function createPlaylist() {
    if (!window.confirm("Do you want to generate this playlist?")) {
      return;
    }
    axios
      .post(
        "https://api.spotify.com/v1/users/" + userId + "/playlists",
        {
          name: `${rangesTitles[selectedRange]} Top Tracks`,
          public: "true",
          collaborative: "false",
          description: "This playlist was generated by myspotifyprofile.com",
        },
        {
          headers: {
            Authorization: "Bearer " + localStorage.getItem("accessToken"),
            "Content-Type": "application/json",
          },
        }
      )
      .then((res) => {
        const playlistId = res.data.id;
        console.log(playlistId);
        axios
          .get(
            `https://api.spotify.com/v1/me/top/tracks?time_range=${selectedRange}_term&limit=50`,
            {
              headers: {
                Authorization: "Bearer " + localStorage.getItem("accessToken"),
                "Content-Type": "application/json",
              },
            }
          )
          .then((res) => {
            const tracks = res.data.items;
            console.log(tracks);
            const trackUris = [];
            for (const track of tracks) {
              trackUris.push(track.uri);
            }
            axios
              .post(
                "https://api.spotify.com/v1/playlists/" +
                  playlistId +
                  "/tracks",
                {
                  uris: trackUris,
                  position: 0,
                },
                {
                  headers: {
                    Authorization:
                      "Bearer " + localStorage.getItem("accessToken"),
                    "Content-Type": "application/json",
                  },
                }
              )
              .then((res) => {
                console.log(res);
                alert(
                  "Playlist successfully created! It should appear in your library very soon."
                );
              })
              .catch((err) => {
                if (err.response.status === 401) Spotify.authReq();
              });
          })
          .catch((err) => {
            if (err.response.status === 401) Spotify.authReq();
          });
      })
      .catch((err) => {
        if (err.response.status === 401) Spotify.authReq();
      });
  }

  const [selectedRange, setSelectedRange] = useState("short");
  const ranges = ["short", "medium", "long"];
  const rangesTitles = {
    short: "Most Recent",
    medium: "Recent",
    long: "All Time",
  };
  const rangeImgSrc = {
    short: Spotify.homepage + "/mostRecentTopTracks.jpg",
    medium: Spotify.homepage + "/recentTopTracks.jpg",
    long: Spotify.homepage + "/allTimeTopTracks.jpg",
  };
  function changeRange(e) {
    setSelectedRange(e.target.value);
    window.scrollTo(0, 0);
  }
  return (
    <>
      <div id="header" className=" bg-white z-10">
        <label htmlFor="selector" className="z-10 bg-white">
          Time Range:
        </label>
        <select
          id="selector"
          className="z-10"
          value={selectedRange}
          onChange={changeRange}
        >
          {ranges.map((option, index) => (
            <option key={index} value={option}>
              {option}
            </option>
          ))}
        </select>
      </div>
      <div>
        <img
          onClick={createPlaylist}
          src={rangeImgSrc[selectedRange]}
          alt="Create Playlist"
          className=" w-36 h-36"
        />
      </div>
    </>
  );
}

export default TopTracksPlaylist;
